#! /bin/bash
#
# docker/makedist -- make all components from this repo via the docker containers
#                    defined in the docker directory.
#
# Usage: docker/makedist [--dist-dir=DIR] [python|angular|midas-portal|midas-nps] ...
#
# where:
#   --dist-dir=DIR     write component distributions to the given directory
#                      (instead of the default directory, dist)
#   python             build only the python-based distributions
#   angular            build only the angular-based distributions
#
#   midas-portal       build the portal application
#   npsbroker          build the NPS proxy service
#

prog=`basename $0`
execdir=`dirname $0`
[ "$execdir" = "" -o "$execdir" = "." ] && execdir=$PWD
export CODEDIR=`(cd $execdir/.. > /dev/null 2>&1; pwd)`
export DOCKERDIR=$execdir

os=`uname`
SED_RE_OPT=r
[ "$os" != "Darwin" ] || SED_RE_OPT=E

#This is a repo level scripts directory
scriptsdir=$CODEDIR/scripts

buildpy=1
[ $# == "0" ] || buildpy=`echo " $@ " | egrep " npsbroker | python "`
buildang=1
[ $# == "0" ] || buildang=`echo " $@ " | egrep " midas-portal | angular "`
args=`echo " $@ " | sed -${SED_RE_OPT}e 's/ (npsbroker|midas-portal|angular|python) / /g'`

if [ -n "$buildpy" ]; then
    # No special docker environment is required to build
    # the npsbroker; we can do it natively
    echo "Building npsbroker (natively)"
    $scriptsdir/makedist.npsbroker $args
fi

if [ -n "$buildang" ]; then
    echo "Building midas-portal via docker"
    exec $DOCKERDIR/run.sh build $args angular
fi

